name: Packj Audit GitHub Action Demo

on:
  pull_request:
    branches:
      - main

jobs:
  packj-security-audit:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:   
      - name: Audit dependencies
        uses: ossillate-inc/packj-github-action@main
        with:
          DEPENDENCY_FILES: npm:package.json
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
