name: Packj Audit GitHub Action Demo

on:
  pull_request:
    branches:
      - main

jobs:
  packj-security-audit:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - run: echo "Run audit triggered automatically by a ${{ github.event_name }} event."

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Audit dependencies
        uses: ossillate-inc/packj-github-action@main
        with:
          DEPENDENCY_FILES: npm:package.json
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
